branch-defaults:
  master:
    environment: lucy
global:
  application_name: Lucy
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.0 running Python 3.4
  default_region: us-east-1
  profile: eb-cli
  sc: git
